server:
  port: 9527

spring:
  application:
    name: cloud-gateway
#############################新增网关配置###########################
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: payment_routh #payment_route    #路由的ID，没有固定规则但要求唯一，建议配合服务名
          #uri: http://localhost:8001          #匹配后提供服务的路由地址
          uri: lb://CLOUD-PROVIDER-PAYMENT #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/**         # 断言，路径相匹配的进行路由
            #- Between=2021-11-01T15:42:46.966+08:00[Asia/Shanghai], 2025-11-01T15:42:46.966+08:00[Asia/Shanghai]
            #- Cookie=username,lixuan
            - Header=X-Request-Id, \d+ # 带指定请求头的参数为正整数
            #- Method=GET
            #- Query=username,\d+ 参数要有username并且是整数才能路由
            # 带指定请求头的参数的CURL命令
            # curl http://localhost:9527/payment/lb -H "X-Request-Id:123"
        #curl http://localhost:9527/payment/lb --cookie "username=lixuan" #curl测试语句
        - id: payment_routh2 #payment_route    #路由的ID，没有固定规则但要求唯一，建议配合服务名
          #uri: http://localhost:8001          #匹配后提供服务的路由地址
          uri: lb://CLOUD-PROVIDER-PAYMENT #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/lb         # 断言，路径相匹配的进行路由
            - After=2021-11-01T15:42:46.966+08:00[Asia/Shanghai] #Before同理
            - Cookie=username,lixuan
#curl http://localhost:9527/payment/lb --cookie "username=lixuan" #curl测试语句
####################################################################

eureka:
  client:
    #表示是否将自己注册进EurekaServer默认为true。
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetchRegistry: true
    service-url:
      defaultZone: http://localhost:7001/eureka
      #defaultZone: http://localhost:7001/eureka,http://localhost:7002/eureka #集群版
  instance:
    instance-id: cloud-gateway
    prefer-ip-address: true #暴露ip