server:
  port: 9004

spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.64.128:80 #配置Nacos地址

management:
  endpoints:
    web:
      exposure:
        include: '*'
